In [3]:
import pandas as pd

# Wczytanie danych z pliku CSV
df = pd.read_csv('data.csv', index_col=0)
df

,users,pascha wielkanocna,spaghetti bolognese,lazania,pierogi,czebureki,babka ziemniaczana,kaszanka,kutia,Pizza Neapolitanska,...,Barszcz czerwony,Schabowy,gnocchi z chorizo i szpinakiem,Grzanka z serem,Kotlety mielone,Kebab,Tagliatelle z szynką parmeńską w sosie śmietanowym,Krewetki,Sushi,kanapka serem i czekoladą
Ula,4.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Monika,NaN,NaN,NaN,NaN,5.0,NaN,5.0,3.0,NaN,4.0,...,5.0,NaN,NaN,NaN,3.0,NaN,NaN,2.0,NaN,NaN
Maciek,2.0,NaN,5.0,5.0,NaN,4.0,1.0,1.0,NaN,5.0,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kasper,1.0,NaN,1.0,NaN,2.0,NaN,1.0,NaN,5.0,1.0,...,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Filip,NaN,NaN,5.0,5.0,4.0,NaN,4.0,3.0,NaN,1.0,...,3.0,5.0,NaN,NaN,4.0,5.0,NaN,NaN,NaN,NaN
Ola,NaN,3.0,NaN,2.0,5.0,NaN,4.0,1.0,2.0,NaN,...,5.0,3.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
Patrycja,NaN,NaN,NaN,4.0,4.0,NaN,0.0,1.0,NaN,5.0,...,NaN,4.0,NaN,3.0,NaN,4.0,5.0,1.0,4.0,NaN
Juliusz,NaN,NaN,NaN,5.0,5.0,NaN,5.0,NaN,NaN,5.0,...,3.0,5.0,NaN,NaN,3.0,5.0,5.0,NaN,NaN,NaN
Matusz,NaN,NaN,4.0,5.0,5.0,NaN,5.0,4.0,NaN,NaN,...,3.0,5.0,NaN,4.0,1.0,NaN,NaN,1.0,NaN,NaN
Konrad,NaN,NaN,NaN,NaN,5.0,NaN,5.0,NaN,NaN,5.0,...,5.0,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN
Rafał,NaN,NaN,2.0,NaN,NaN,NaN,2.0,NaN,NaN,4.0,...,NaN,5.0,4.0,NaN,NaN,NaN,NaN,NaN,4.0,3.0
Andrzej,NaN,NaN,NaN,5.0,5.0,NaN,3.0,NaN,5.0,NaN,...,NaN,5.0,NaN,3.0,3.0,NaN,5.0,NaN,3.0,NaN
Mateusz Daniel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,5.0,3.0,4.0,5.0,5.0,5.0,1.0,5.0,5.0