In [10]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

df = pd.read_csv('data.csv', index_col=0).fillna(0)
df

,users,pascha wielkanocna,spaghetti bolognese,lazania,pierogi,czebureki,babka ziemniaczana,kaszanka,kutia,Pizza Neapolitanska,...,Barszcz czerwony,Schabowy,gnocchi z chorizo i szpinakiem,Grzanka z serem,Kotlety mielone,Kebab,Tagliatelle z szynką parmeńską w sosie śmietanowym,Krewetki,Sushi,kanapka serem i czekoladą
Ula,4.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Monika,0.0,0.0,0.0,0.0,5.0,0.0,5.0,3.0,0.0,4.0,...,5.0,0.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,0.0
Maciek,2.0,0.0,5.0,5.0,0.0,4.0,1.0,1.0,0.0,5.0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kasper,1.0,0.0,1.0,0.0,2.0,0.0,1.0,0.0,5.0,1.0,...,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Filip,0.0,0.0,5.0,5.0,4.0,0.0,4.0,3.0,0.0,1.0,...,3.0,5.0,0.0,0.0,4.0,5.0,0.0,0.0,0.0,0.0
Ola,0.0,3.0,0.0,2.0,5.0,0.0,4.0,1.0,2.0,0.0,...,5.0,3.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
Patrycja,0.0,0.0,0.0,4.0,4.0,0.0,0.0,1.0,0.0,5.0,...,0.0,4.0,0.0,3.0,0.0,4.0,5.0,1.0,4.0,0.0
Juliusz,0.0,0.0,0.0,5.0,5.0,0.0,5.0,0.0,0.0,5.0,...,3.0,5.0,0.0,0.0,3.0,5.0,5.0,0.0,0.0,0.0
Matusz,0.0,0.0,4.0,5.0,5.0,0.0,5.0,4.0,0.0,0.0,...,3.0,5.0,0.0,4.0,1.0,0.0,0.0,1.0,0.0,0.0
Konrad,0.0,0.0,0.0,0.0,5.0,0.0,5.0,0.0,0.0,5.0,...,5.0,0.0,0.0,0.0,5.0,5.0,0.0,0.0,0.0,0.0
Rafał,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,4.0,...,0.0,5.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0,3.0
Andrzej,0.0,0.0,0.0,5.0,5.0,0.0,3.0,0.0,5.0,0.0,...,0.0,5.0,0.0,3.0,3.0,0.0,5.0,0.0,3.0,0.0
Mateusz Daniel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,5.0,3.0,4.0,5.0,5.0,5.0,1.0,5.0,5.0

In [11]:
scaler = StandardScaler()
scalar_fit = scaler.fit_transform(df)

In [12]:
kmeans = KMeans(n_clusters=5)
kmeans.fit(scalar_fit)
df['Cluster'] = kmeans.predict(scalar_fit)
df

,users,pascha wielkanocna,spaghetti bolognese,lazania,pierogi,czebureki,babka ziemniaczana,kaszanka,kutia,Pizza Neapolitanska,...,Schabowy,gnocchi z chorizo i szpinakiem,Grzanka z serem,Kotlety mielone,Kebab,Tagliatelle z szynką parmeńską w sosie śmietanowym,Krewetki,Sushi,kanapka serem i czekoladą,Cluster
Ula,4.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
Monika,0.0,0.0,0.0,0.0,5.0,0.0,5.0,3.0,0.0,4.0,...,0.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,0.0,3
Maciek,2.0,0.0,5.0,5.0,0.0,4.0,1.0,1.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
Kasper,1.0,0.0,1.0,0.0,2.0,0.0,1.0,0.0,5.0,1.0,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
Filip,0.0,0.0,5.0,5.0,4.0,0.0,4.0,3.0,0.0,1.0,...,5.0,0.0,0.0,4.0,5.0,0.0,0.0,0.0,0.0,0
Ola,0.0,3.0,0.0,2.0,5.0,0.0,4.0,1.0,2.0,0.0,...,3.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,3
Patrycja,0.0,0.0,0.0,4.0,4.0,0.0,0.0,1.0,0.0,5.0,...,4.0,0.0,3.0,0.0,4.0,5.0,1.0,4.0,0.0,4
Juliusz,0.0,0.0,0.0,5.0,5.0,0.0,5.0,0.0,0.0,5.0,...,5.0,0.0,0.0,3.0,5.0,5.0,0.0,0.0,0.0,4
Matusz,0.0,0.0,4.0,5.0,5.0,0.0,5.0,4.0,0.0,0.0,...,5.0,0.0,4.0,1.0,0.0,0.0,1.0,0.0,0.0,0
Konrad,0.0,0.0,0.0,0.0,5.0,0.0,5.0,0.0,0.0,5.0,...,0.0,0.0,0.0,5.0,5.0,0.0,0.0,0.0,0.0,0
Rafał,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,4.0,...,5.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0,3.0,1
Andrzej,0.0,0.0,0.0,5.0,5.0,0.0,3.0,0.0,5.0,0.0,...,5.0,0.0,3.0,3.0,0.0,5.0,0.0,3.0,0.0,4
Mateusz Daniel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,3.0,4.0,5.0,5.0,5.0,1.0,5.0,5.0,1